<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<IsPackable>true</IsPackable>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);CS1591</NoWarn>
		<Description>UniversalRemote Abstractions preview SDK.</Description>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>
	<ItemGroup>
		<None Include="../../README.md" Pack="true" PackagePath="/" />
	</ItemGroup>
</Project>