<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
    <RootNamespace>UniversalRemote.Remote.Core</RootNamespace>
		<IsPackable>true</IsPackable>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);CS1591</NoWarn>
		<Description>UniversalRemote Core preview SDK.</Description>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="../UniversalRemote.Abstractions/UniversalRemote.Abstractions.csproj" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
		<None Include="../../../README.md" Pack="true" PackagePath="/" />
	</ItemGroup>
</Project>